name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "./"

      - name: Yamllint
        uses: karancode/yamllint-github-action@master

  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Molecule test
#        uses: robertdebock/molecule-action@2.0.0
        uses: normo/molecule-action@jmespath
